### ISSUE TITLE
path.js Throwing TypeError

### ISSUE THREAD

**Issue by willdavidow** [shakyShane/bs-snippet-injector#4]
The following code within my gulp task is throwing an error:

```

    var browserSync = require('browser-sync'),
    bsInjector      = require('bs-snippet-injector');

    browserSync.use(bsInjector, {
            file: 'theme/footer.php'
    });

    browserSync({
        files: [
            config.dirs.theme + '/**/*.php',
            config.dirs.theme + '/style.css',
            config.dirs.theme + '/' + config.dirs.js + '/**/*.js'
        ]
    )};
```

Here is error output when running gulp:

```
$ gulp
[13:40:37] Using gulpfile /Dev/test/gulpfile.js
[13:40:37] Starting 'sass-dev'...
[13:40:37] Finished 'sass-dev' after 8.72 ms
[13:40:37] Starting 'copy-dev'...
[13:40:37] Finished 'copy-dev' after 403 ms
[13:40:37] Starting 'default'...
[13:40:38] Finished 'default' after 268 ms
path.js:422
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:422:13)
    at module.exports.plugin (/Dev/test/node_modules/bs-snippet-injector/index.js:41:37)
    at null.<anonymous> (/Dev/test/node_modules/browser-sync/node_modules/easy-extender/index.js:55:41)
    at Array.forEach (native)
    at EasyExtender.initUserPlugins (/Dev/test/node_modules/browser-sync/node_modules/easy-extender/index.js:46:21)
    at Object.module.exports.initUserPlugins [as fn] (/Dev/test/node_modules/browser-sync/lib/async.js:251:26)
    at /Dev/test/node_modules/browser-sync/lib/browser-sync.js:135:14
    at iterate (/Dev/test/node_modules/browser-sync/node_modules/async-each-series/index.js:8:5)
    at /Dev/test/node_modules/browser-sync/node_modules/async-each-series/index.js:16:16
    at executeTask (/Dev/test/node_modules/browser-sync/lib/browser-sync.js:156:13)
```

The file I'm attempting to inject to is in place at the location being referenced in 'file' and I was not receiving this error before I started using bs-snippet-injector.

Any thoughts? Please let me know if you need more details.

Thanks!

**Comment by shakyShane** [comment]
Fixed in 2.0.0 :)
